export const gameData = {
  playerCountMin: 2,
  playerCountMax: 5,
  cityCount: 20,
  cityNames: [
    'New York',
    'Ottawa',
    'Mexico',
    'Rio',
    'Santiago',
    'Glasgow',
    'Paris',
    'Marrakech',
    'Oslo',
    'Moscou',
    'Budapest',
    'Le Caire',
    'Kinshasa',
    'Nairobi',
    'Durban',
    'New Delhi',
    'Pékin',
    'Séoul',
    'Kyoto',
    'Sydney',
  ],
  cityStart: 0,
  wasteCount: 3,
  wasteNames: ['ménager', 'naturel', 'industriel'],
  supportCount: 3,
  supportNames: ['population', 'industrie', 'politique'],
  solutionCardsCount: 50,
  pollutionCardsCount: 50,
  maxCityWasteCount: 4,
  maxHandCardsCount: 7,
  actionsPerTurn: 3,
  maxSupportLevel: 4,
  maxCopLevel: 4,
  maxOceanWasteCount: 4,
}
